maleName = input("Male name: ")
femaleName = input("Female name: ")
color = input("Color: ")
candy = input("Candy: ")
adjective = input("Adjective: ")
animal = input("Animal: ")
place = input("Place: ")

print("There once was a Prince named {0} who was on a quest to save princess {1} from danger!".format(maleName, femaleName))
print("Princess {0} was locked in a tower and guarded by a {1} {2} {3}!".format(femaleName, adjective, color, animal))
print("Prince {0} approached the tower and spotted the {1}. He noticed it looked hungry and pulled out a {2}.".format(maleName, animal, candy))
print("The {0} immediately was facinated by the {1}, so {2} threw the {1} to satisfy the hunger of the {0}".format(animal, candy, maleName))
print("The {0} {1} suddenly became friendly and started to follow Prince {2} as he worked to rescue the princess.".format(adjective, animal, maleName))
print("Prince {0} was able to rescue Princess {1} and they lived with their new pet {2} in their castle in {3}!".format(maleName, femaleName, animal, place))
print("They Lived Happily Ever After!")